name: 发布NPM包

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          # 确保使用npm进行发布
          scope: "@agions"

      - name: 安装依赖
        run: npm install --legacy-peer-deps

      # - name: 运行测试
      #   run: npm test

      - name: 构建
        run: npm run build:prod

      - name: 配置NPM认证
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 发布到NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 更新发布状态
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const release = context.payload.release;
            if (release) {
              await github.rest.repos.updateRelease({
                owner,
                repo,
                release_id: release.id,
                body: release.body + "\n\n✅ NPM包已成功发布！"
              });
            }
